repos:

- repo: https://github.com/miki725/importanize
  rev: '0.7'
  hooks:
  - id: importanize
    language_version: python3

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-byte-order-marker
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
  - id: flake8
    additional_dependencies:
      - flake8-bugbear
      - flake8-comprehensions

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
