repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      types: [python]
      exclude: (migrations/)
-   repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      files: \.py$
      log_file: '.artifacts/flake8.pycodestyle.log'
      additional_dependencies:
      - sentry-flake8==0.4.0
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
      exclude_types: [svg]
    - id: trailing-whitespace
      exclude_types: [svg]
    - id: debug-statements